### ISSUE TITLE
Is there any reason this is not on Hex?

### ISSUE THREAD

**Issue by lawik** [visciang/telegram#139]
I know :telegram is taken but I assume it could be published with another name on Hex.pm.

It would be convenient and I think it is a nice and useful library so I find it odd that it is only available via GitHub.

Is there a reason?

**Comment by visciang** [comment]
It started as a personal project and my rule of thumb is to avoid namespace pollution in hex (... the anti-NPM syndrome).
BTW if you find any blockers while consuming it via git let me know.

**Comment by lawik** [comment]
Going to use it in a talk so figured it might be more convenient for people who want to try it. No big deal :)

thanks for building it ✨
