### ISSUE TITLE
`ChatBot` running in `Poller` mode gets `{:error, "Too Many Requests: retry after 5"}`

### ISSUE THREAD

**Issue by samm81** [visciang/telegram#145]
first, thanks for the library!

I'm running the `ChatBot` in `Poller` mode and after a while it starts getting `{:error, "Too Many Requests: retry after 5"}` every 10th of a second or so for a couple minutes before eventually dying all together (too many failures I suppose).

Is this an unhandled case that I could contribute somehow? Or can I set a larger polling timeout somewhere?

**Comment by visciang** [comment]
Hi @samm81,

can you show me a simple bot that triggers the telegram rate limit (I suppose on the "getUpdates" request)?
It will be useful to check the current config you are using (for example if you have a custom value for the [:telegram, :get_updates_poll_timeout_s] config), which tesla client etc.
  
You could start from the telegram/example/example_bot.exs and tweak it to show the issue.
(BOT_TOKEN="...your token..." ./example/example_bot.exs).

Thank you!

**Comment by visciang** [comment]
Check out #146 .
I've included a retry rule in case of server side throttling.
Released in v0.22.3.

BTW, this should not happen in your case, even with a `get_updates_poll_timeout_s = 0` the telegram server does not send me a 429, it just slow me down. Maybe this could happen if you send lots of messages ion a tight loop.

Please investigate a bit more on your side.

I'm closing this issue for now, feel free to ping back if your have any additional details or question.

**Comment by samm81** [comment]
hi, thanks for the quick response!

definitely nothing crazy for my config, `config :tesla, adapter: {Tesla.Adapter.Hackney, [recv_timeout: 30_000]}` is all. I'm definitely not sending messages in a tight loop. I did set the `max_bot_concurrency: 1`, as I was only expecting to have one client (me), maybe that's it?

I will try `v0.22.3`, seems I was a whole minor version behind (`v0.22.0`), thanks again!

**Comment by visciang** [comment]
Yes, nothing strange.

FYI in https://github.com/visciang/telegram/pull/144 (release 0.22..2) I've removed a incorrect retry logic that was applied also to errors raising from the bot.

BTW If you can hit the problem consistently, please try with 0.22.3 and keep an eye at the logs.

PS: `recv_timeout` should be strictly greater than the HTTP long polling timeout (`get_updates_poll_timeout_s` defaults to 30s), for example 40s is fine. I've updated the docs recently.
