### ISSUE TITLE
handle_info in Telegram.ChatBot

### ISSUE THREAD

**Issue by julienmarie** [visciang/telegram#154]
Would it be possible to implement the handle_info callback in ChatBot ?
Would be pretty useful to be able to update state of conversation based on other event or async processes.

**Comment by visciang** [comment]
Sure, would you like to start a PR?

I think we can add an optional callback on the behaviour, what do you think?

**Comment by julienmarie** [comment]
Gladly but I would need a little bit of guidance. Your elixir is way more advanced than mine. Trying to wrap my head around the session server

**Comment by visciang** [comment]
Done in #157 !

**Comment by julienmarie** [comment]
Amazing !
