### ISSUE TITLE
[Question] How should I call the DSL from webhooks

### ISSUE THREAD

**Issue by eaguilera23** [visciang/telegram#43]
I see the macro `command` for example, or `inline_query`, and I understand how to make calls from the bot to telegram, but how is the bot getting the calls from telegram?

If a user makes an inline query like `@mybot query`, how does the `DSL` gets this into the macro `inline_query`. Should I call something from the webhook? Or is the bot getting updates instantaneously?

BTW Thank you, it is a pretty interface and better that it supports multiple bots as I understand. Thank you for the effort and I look forward to contributing ❤️

**Comment by visciang** [comment]
Hi @eaguilera23 
yes, the bot receives an update instantaneously (https://core.telegram.org/bots/api#update).

The `Update` object received is of type `inline_query` and contains the `query` part in your inline query as you type.

This is an example of update received when typing `@mybot query abc`.

```elixir
%{
  "inline_query" => %{
    "from" => %{
      "first_name" => "YYYYY",
      "id" => 12345678,
      "is_bot" => false,
      "language_code" => "en",
      "last_name" => "XXXX",
      "username" => "bbbbbb"
    },
    "id" => "9876543210",
    "offset" => "",
    "query" => "query abc"
  },
  "update_id" => 990241896
}
```

You can test it yourself with the example bot included `mix run example/example.exs`.
Just fill:
```elixir
  use Telegram.Bot,
    token: "xxxxxxxx,
    username: "mybot_bot",
    auth: nil,
    purge: true
```

then send the bot messages /commands or an inline_query (note that inline queries are not sent from a direct chat to `mybot`, use a chat with another user to query your bot).

PS: the BOT / DSL in general is just a toy example, when I wrote the library the main scope was the Telegram BOT API interface.
