### ISSUE TITLE
Multiple custom commands not matching

### ISSUE THREAD

**Issue by DonHansDampf** [visciang/telegram#52]
Probably am missing something but how do multiple commands work? I defined them as:
```
  command stats do
    ...
  end
  command check do
    ...
  end
```
but I get the following error:
```
warning: variable "stats" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/comicbot/telegram.ex:8: Comicbot.Telegram.handle_update/2

warning: this clause cannot match because a previous clause at line 8 always matches
  lib/comicbot/telegram.ex:15
```

Thank you very much!

**Comment by visciang** [comment]
Ciao, commands should be string or list of strings (ref. examples).

Currently the command macro is expanded as a series of function clauses pattern matching the update message received.

Have a look at the macro https://github.com/visciang/telegram/blob/master/lib/bot.ex quote_handle_update_for_command(text, args, body).

BTW, the bot implementation is just a very basic toy, it's a simple prototype.

**Comment by DonHansDampf** [comment]
Hello visciang,
thank you for the explanation and pointing me in the right direction! Dunno why i didn't try it myself to simply use some string match at `update["text"]`... Any way, thank you very much!
I already read about that the macros are just some prototype, but it's really convenient to use, so i wanted to try it out :)
